language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck
before_script: /home/travis/.luarocks/bin/luacheck . -qo "011"

notifications:
  email:
    on_success: never
    on_failure: always
