sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "SOHSKOLwYLAXOh4FkxaxstUmfDUSD/wqrUkldELoFqO45hUrTWWrIQrJOyMo864eyhYQFzvp4HHCKNxfG63tkbw7iaY15Q+VkEP6ojG+efgns8NdegJawvJ9Z4Ge5KyMhKpQnjr2p4ai8+hj3AV9QZzya3smgcGFzK9HmdzY2EbtaD3r7nLfMJng1GA5lE2G+VecMXDNVrPsF1RRnD4be3HcCzpY0Oxj9PKcbZTnFpb4SSh4s8aQDhk+g8YwiS9zC525p4HENBPVDM7GPUqAQFC/YjkmsdqLd9Ww2lKrYRECCGhA0esIteTuwwlHdzUtD48oEdtQ4Gzi0h4dIS+yErQWkyjmawhEWye2L3fGTzQf8LqGqFOZq96WHAlndhvKrJinYzujKprnsdUvAwtZDjGqB16rqq7dYjk2LVtsrqwE1mLJAeUA5bj0twMXwD2gz9+rQlHMXkNtJ64W4rKj4fBMj4+g5gvluxCKCfra71I+zAdqJN84TnZhzFEtJx9JidENZBmoMn2OCXdm/BSNpQxr5L/hZCWNa/kpO905k0tkV0Bnoo+8yi7BdQp70mgxG6tAziQZ17VdV0bhDIp3ZVblzRc25GeSNxgDudwBaDlPAT8+gZEhQlXLZwm5i2Vi/3UErSlK2vdg2bOZohgmTE+/N8AO3UlHZmeSrxMu94k="
  - secure: "eSDWY3h8TBnAHauU175EEhfNNn65dBjLJsnKRVKslTnDUpVf8E3pSgHEHEa7oikjT4dWeeLTzhK7FRtuthTZaOMDS+tZv6ESPY7s8L1vZHEnEAtvKy3eYLiMfD2oXJtMnE+t+Y1XSCNnvWAFGmmMwstG//fkwTO0nTdHmcNLUQAy4wg73bqVeBROjqr4ANi9ivYgfdk+a3Pl0yt2CxUIoSADdQeM00bX+m+U/ZfYKmTX+ET7jXzIO/9JGTjl9aKnHxYtCnT/wBspD5g11r80EIufc/E/O9oiWzOsXdXZLu4RsSbQcRCuLZqEpl6PQBoxEXOcwkkH+T17o/QDJHNT/YXw7q1UmHmGkzHlV+hZIjgG8tENGfn7ArWW5jYsv8rWov/yExf5JLiSkdwIdtjotGe/VWYT6pngUSfehc+WQOOYf2UT8AIdm6K5bzPp+f6KUAkFBhe4QdBFv6uxTlUmrURhyGqZj5NliNfwbkUPn+izJJwQjDX2rEmkyiajZgBnXeDFIALWzwFlbEQw/ftPrbJ6Te5OKy03kfjxdG9/VJRrQZK9+kufZ8ESs1y4QhjTYLUbtsgf7oRDVSgB1dizlMTfvnEYMzEUT0jWZUe9FArObLe+NXmvqKm0wvf8CPgXZB61AOgyo/F/hZ+4WppjMxm9aXJSvCm4bRb7gu8E9c4="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p transcriptor

notifications:
  email:
    on_success: never
    on_failure: always
