sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "DyDuXxdNufWcOt4iYsG6ThrcQ1LfUzuMmbSMFfSeSCoJe0o4yYVSqhcHkuv4Hj3b2tuh/JTMIJIQVxU+Nsld0MDaIPhC0ulraSKd6+E2En6BlWRaxucRAMcgg+3gtTahkteSjwdDd4Djq4TgqNjAcvhfxWCTeDAZyf0FMa24f56MAfVyFaPEgpiB1VngOqcFB1bfIdkhqqmHOEIvELLAqUDMu+7BnlSdQeyL1+LZreG6u7By5heAStxLrtrqjm2IX9vfl5fkAXYL3iDA6nGEUDCxsqbagvUNsFQb2C3sjPFsvEapbsGU2HPFF8nbuYr7jnbCAcgNMh6C2SsLUiUYiYExQiAaQwKIjpvn+fjhR7dL3d9xakZH0QDcoGp70/1hGPXTH8hHxjEk16hGD21p6GumEqAlnqIM8MSTje/zm4tlDlIF3BDsYCbkwqyTy8aY6WcOC2OnBDo90jWS789S82ZAssh43C+1W13xgjsTP1e4X7cJjdjSUJt5eMcyjhW3l5R+yaFK0m9PQHxxdSK3UNNVDSHDtstMHHShVkqvkjOMOzLYxs9iQ1KqMRiE13mYPPFWm1Kl+j5cjX4Ka31P9J6gc9zxl3yPYYDVFKMd1GWeCA+o9NvNx6i+XSDqIFpO2/J7xYgGpfrWtYPSNpxyjUWKNrDJuDPKrb7+fMmQLNY="
  - secure: "b9K95hNjad4buZBtDnivUslKO8oElS0pDEkuDrVNmujMGflPCRPARkZSbkfoP4xVrBivBTqAEVyjLYjPCJNEAb9L+GuikMk1vtt2jFuj9V+xYJ9QFNQ67mHNDTt6Ac5EXYm7jD4yHcgcPJjxvG3+Db/v7g3QY1JaSwddmSisyPH6J8EIe1HLYlLoC2S14yNKc/oPiy+nc/fkfQG6UX55e3SANk9Dtb8wb/E043w+QxKiQvvdpzx9FREipaf9lVl9Bj1e7jT6SMn2yp6TxKcY0+Cpyz1i+hTdcL5vBDHx7BIAEVu/qpBY4rPf4K44zy5pcfxctLeKRgdYov3+uOuFkQ2B8z+fKf0MmpIoHoZlGXwHeuSNbiE351bsyKUGH7sjeZ1nw2G+3BCWBLVnolIR7JSFZhSoAnRF8F1frBiHhFX+/tP56wE0fAjomFZjmp+awxyc7D2w7UUli7i9OCwfJpZ9fdOd22gbdGkyxDJ4AgLxnmyDZsz39YJAq+vwtELxIbvKaIqx+EUdg45wt/ANrfnVrVMiGZud92lVNK7TETVa3Lo+THBR9rmXneY5fXmiLVtf+09dXvFK+2ZygD0o5/qweRdTLnq9lfvjYwT3oBlWtjSuZkLf6LNZHop2X2se/5nAwdkV6Cn71FATaTr6d/LmwHxucq0WY3QjXdEN3Sw="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
