sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "b5fY+I9J4ZOUQRUWrHpsM87YzuwVnJttSF6L7gZoMIaIJ4aNMWuY3GQnt+uDDA1E2hNXvZwK2RF7ge6ujdQnQWjxjZt6t2yyQqvEJ/YxZmm1Pk2JWCQEu1CdIQfrFbQ5Vl9+fSbTt9mG6IZnlkIpA1zQZHAybBF/i+8Riwgv+3/dHX80d040v7GtWB4c+lTsTp4pBfLmJReww9/1bGCTac2h4lL09UXTikwvMTNC0vlyKFbZyi6X/vhI9l056Yq5HaiNPPLgHNRook3UU6u6LRmxZjRSxte3Ate0ulX3VAhrZ7+Hkg5608It9guVZ/PMnUNWkVwEz6EC8DFkoKkm/1PlA21YM4KX1a/Q0+sX3pXz1Ci9pgMP5GXGcgOMYfliAgwJozLjAGC9S+viqrOwIE75ga4Eb0ervgKjLgyS1YpstjBlJpLLiSfZfK2UWi+iEI1MJVM8GHtZEr8DZK9OqUXUWwgURIecSFiYd0z4Ce2Pi2N7h0ryDC9SCh2H7ytLhJ0sbmiMKcA/w2WTf9VnIKz52/KWL871t4me7/5XiYn8s8A74XUIE9F38YrUzz0d5Wmhrq9DRltMjdsZYgaYawD9pCPwUdrjNkNBXpLX+T9Nq7aqrZeruDX5olb8LT3hMnzXD9V0/RSzn7gRO1i1xFxgsJbmbDzIKtlJE1Ehl1w="
  - secure: "b9K95hNjad4buZBtDnivUslKO8oElS0pDEkuDrVNmujMGflPCRPARkZSbkfoP4xVrBivBTqAEVyjLYjPCJNEAb9L+GuikMk1vtt2jFuj9V+xYJ9QFNQ67mHNDTt6Ac5EXYm7jD4yHcgcPJjxvG3+Db/v7g3QY1JaSwddmSisyPH6J8EIe1HLYlLoC2S14yNKc/oPiy+nc/fkfQG6UX55e3SANk9Dtb8wb/E043w+QxKiQvvdpzx9FREipaf9lVl9Bj1e7jT6SMn2yp6TxKcY0+Cpyz1i+hTdcL5vBDHx7BIAEVu/qpBY4rPf4K44zy5pcfxctLeKRgdYov3+uOuFkQ2B8z+fKf0MmpIoHoZlGXwHeuSNbiE351bsyKUGH7sjeZ1nw2G+3BCWBLVnolIR7JSFZhSoAnRF8F1frBiHhFX+/tP56wE0fAjomFZjmp+awxyc7D2w7UUli7i9OCwfJpZ9fdOd22gbdGkyxDJ4AgLxnmyDZsz39YJAq+vwtELxIbvKaIqx+EUdg45wt/ANrfnVrVMiGZud92lVNK7TETVa3Lo+THBR9rmXneY5fXmiLVtf+09dXvFK+2ZygD0o5/qweRdTLnq9lfvjYwT3oBlWtjSuZkLf6LNZHop2X2se/5nAwdkV6Cn71FATaTr6d/LmwHxucq0WY3QjXdEN3Sw="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
