sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: SOHSKOLwYLAXOh4FkxaxstUmfDUSD/wqrUkldELoFqO45hUrTWWrIQrJOyMo864eyhYQFzvp4HHCKNxfG63tkbw7iaY15Q+VkEP6ojG+efgns8NdegJawvJ9Z4Ge5KyMhKpQnjr2p4ai8+hj3AV9QZzya3smgcGFzK9HmdzY2EbtaD3r7nLfMJng1GA5lE2G+VecMXDNVrPsF1RRnD4be3HcCzpY0Oxj9PKcbZTnFpb4SSh4s8aQDhk+g8YwiS9zC525p4HENBPVDM7GPUqAQFC/YjkmsdqLd9Ww2lKrYRECCGhA0esIteTuwwlHdzUtD48oEdtQ4Gzi0h4dIS+yErQWkyjmawhEWye2L3fGTzQf8LqGqFOZq96WHAlndhvKrJinYzujKprnsdUvAwtZDjGqB16rqq7dYjk2LVtsrqwE1mLJAeUA5bj0twMXwD2gz9+rQlHMXkNtJ64W4rKj4fBMj4+g5gvluxCKCfra71I+zAdqJN84TnZhzFEtJx9JidENZBmoMn2OCXdm/BSNpQxr5L/hZCWNa/kpO905k0tkV0Bnoo+8yi7BdQp70mgxG6tAziQZ17VdV0bhDIp3ZVblzRc25GeSNxgDudwBaDlPAT8+gZEhQlXLZwm5i2Vi/3UErSlK2vdg2bOZohgmTE+/N8AO3UlHZmeSrxMu94k=

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/nebularg/curseforge-packager/master/release.sh | bash -s -- -p transcriptor

before_deploy:
  - export PACKAGER_ARCHIVE=$(ls -1 .release/*.zip | grep -v nolib)
  - echo "Uploading $PACKAGER_ARCHIVE to GitHub release $TRAVIS_TAG"
deploy:
  provider: releases
  api_key:
    secure: lOw6M+/PsS7heQBoRG3lxdczppvQQ1lS6td4BP4IQPacPz1mqKfUOrcfBWtFwPw+v9nqRSE6Ne9ub2ZMinseNT4YsA+qOaozz5Po5uIRp2p/9KF8EfpaBl3+M/c3HLqcfIgNVnp0wTgC+3zkvFHHjuZvbCa2K/v1HEXSOTwI/315HRRxJ3njLYCvw42YF0dHmQB3GeX+nyh2iaT0TV6RYyiv+awbrxeiCdmZ6mOL1C+86UtnI3an5d5tCnJx3uA2VLKAPLtUqzNBuR5yrm+zOOYULH053UNiTe4xJgYXPwPH4zL9clY2Elue3rcIwYPVl/tAJdHGqHK/fJ/ePvhRsVi6Kk4gEmAM2YAUcX5iBk4ElVHlbJHufVnySMB7ZkXEc4tu6VQODTX/ButbmM5K0zafwQXyWI08ATFCwQ20wgYp3wVdqOV5ZK6axDJsJ6Hku2ACeTYu0JZv444Dzd82SaU2xewDWLuHbgsYwVkqWEiW1kuP2krjx57VY2QOMqSRZe/daGNg7ugOiVR7WlU6AdFO85p6NL3PdBzH+bGaZ3R/sYy1++EGZnJNB9gBwiV/NX6Oh1DGWDsl/u/zHpSpmmNd4UBv1LOtwfurkXNi3o7HG2z/VCY6Uw+BzaA2gNFq7iKkqW3FPHYriUsrnQ3mr80b1GfhCR4BRjThmpE8V6A=
  file: "$PACKAGER_ARCHIVE"
  skip_cleanup: true
  on:
    tags: true
